-- Run once in a dedicated Supabase project. Never place service-role keys in the frontend.
create table if not exists public.radar_access (
  email text primary key,
  created_at timestamptz not null default now()
);

create table if not exists public.opportunities (
  id bigint generated by default as identity primary key,
  external_id text not null unique,
  source text not null,
  municipality_code text not null,
  municipality text not null,
  agency text,
  title text not null,
  description text not null default '',
  modality text,
  notice_number text,
  published_at text,
  proposal_end_at text,
  estimated_value numeric,
  url text,
  score integer not null default 0,
  category text,
  matched_terms jsonb not null default '[]'::jsonb,
  status text not null default 'desconhecido',
  favorite boolean not null default false,
  dismissed boolean not null default false,
  notified_at timestamptz,
  alert_baselined_at timestamptz,
  viewed_at timestamptz,
  first_seen_at timestamptz,
  last_seen_at timestamptz,
  raw_json jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_radar_opportunities_city on public.opportunities (municipality_code);
create index if not exists idx_radar_opportunities_score on public.opportunities (score desc);
create index if not exists idx_radar_opportunities_dates on public.opportunities (proposal_end_at);

-- Safe if the schema is rerun after an earlier cloud pilot.
alter table public.opportunities add column if not exists alert_baselined_at timestamptz;

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  opportunity_id bigint references public.opportunities(id) on delete set null,
  channel text not null,
  recipient text,
  status text not null,
  detail text,
  sent_at timestamptz not null default now()
);

create table if not exists public.sync_runs (
  id bigint generated by default as identity primary key,
  source text not null,
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  status text not null,
  found integer not null default 0,
  inserted integer not null default 0,
  updated integer not null default 0,
  detail text
);

alter table public.notifications add column if not exists recipient text;

alter table public.radar_access enable row level security;
alter table public.opportunities enable row level security;
alter table public.notifications enable row level security;
alter table public.sync_runs enable row level security;

create or replace function public.radar_is_authorized()
returns boolean
language sql stable security definer
set search_path = public
as $$
  select exists (
    select 1 from public.radar_access
    where lower(email) = lower(auth.jwt() ->> 'email')
  );
$$;

revoke all on function public.radar_is_authorized() from public;
grant execute on function public.radar_is_authorized() to authenticated;

drop policy if exists radar_opportunities_read on public.opportunities;
create policy radar_opportunities_read on public.opportunities
  for select to authenticated using (public.radar_is_authorized());
drop policy if exists radar_opportunities_update on public.opportunities;
create policy radar_opportunities_update on public.opportunities
  for update to authenticated
  using (public.radar_is_authorized())
  with check (public.radar_is_authorized());
drop policy if exists radar_notifications_read on public.notifications;
create policy radar_notifications_read on public.notifications
  for select to authenticated using (public.radar_is_authorized());
drop policy if exists radar_sync_runs_read on public.sync_runs;
create policy radar_sync_runs_read on public.sync_runs
  for select to authenticated using (public.radar_is_authorized());

revoke all on public.radar_access from anon, authenticated;
revoke all on public.opportunities from anon, authenticated;
revoke all on public.notifications from anon, authenticated;
revoke all on public.sync_runs from anon, authenticated;
grant select on public.opportunities to authenticated;
grant update (favorite, dismissed, viewed_at, updated_at) on public.opportunities to authenticated;
grant select on public.notifications, public.sync_runs to authenticated;

create or replace view public.radar_active_opportunities
with (security_invoker = true)
as
select * from public.opportunities
where not dismissed
  and (
    proposal_end_at is null
    or btrim(proposal_end_at) = ''
    or left(proposal_end_at, 10) >= to_char(now() at time zone 'America/Bahia', 'YYYY-MM-DD')
  );
revoke all on public.radar_active_opportunities from anon, authenticated;
grant select on public.radar_active_opportunities to authenticated;

create or replace function public.radar_dashboard()
returns jsonb
language sql stable security invoker
set search_path = public
as $$
  select jsonb_build_object(
    'total', count(*),
    'open', count(*) filter (where status = 'aberta'),
    'hot', count(*) filter (where score >= 70),
    'favorites', count(*) filter (where favorite),
    'last_update', max(updated_at)
  )
  from public.opportunities
  where not dismissed
    and (
      proposal_end_at is null
      or btrim(proposal_end_at) = ''
      or left(proposal_end_at, 10) >= to_char(now() at time zone 'America/Bahia', 'YYYY-MM-DD')
    );
$$;

revoke all on function public.radar_dashboard() from public;
grant execute on function public.radar_dashboard() to authenticated;

-- After creating a user in Authentication, explicitly allow their email:
-- insert into public.radar_access(email) values ('SEU_EMAIL_AQUI');
